### ISSUE TITLE
Feature Request: Clipboard copying of selected log row

### ISSUE THREAD

**Issue by shawnkelley** [ishegatron/Sentinel#11]
A feature I would find very handy is the ability to Copy (CTRL+C) the select row into clipboard. 
I sometimes have very long debug entries for the description and it can be difficult to read a long line in the log viewer. I realize you can export the whole log, but I'm looking for a quick way to just capture the text of a specific line/row and paste it into a text editor.

**Comment by ishegatron** [comment]
@accenttek I can see how this feature would be useful.  I'll put it on the backlog.

**Comment by ishegatron** [comment]
@accenttek The latest commit 28edc5704cfb5deaf3ad9f4d98ce3c69d8f575a9 now has this feature.
