### ISSUE TITLE
ClickOnce Deployment

### ISSUE THREAD

**Issue by jkoplo** [ishegatron/Sentinel#13]
What would it take to release another version of Sentinel that doesn't use the ClickOnce deployment model? I often need to install Sentinel on machines that are not connected to the internet and ClickOnce has been a pain to deal with in that scenario.

**Comment by ishegatron** [comment]
@jkoplo If your machines are on an internal network, the easiest thing to do would be to build Sentinel yourself and ClickOnce deploy it to some shared network folder.  That way, you get the benefits of automatically updating all of the machines when new versions become available.

If you want to skip the ClickOnce model altogether, the easiest thing to do is just build Sentinel and copy the bin\Release output to every machine.  Again, if the machines are on an intranet and you had admin access to them, you could probably write a PowerShell/batch script to deploy and update them periodically.

The last option is to include some auto-updating code or make a standalone installer project for Sentinel.  I couldn't do this anytime soon, but will certainly take suggestions and pull requests.

**Comment by ishegatron** [comment]
@jkoplo Thanks for contributing!  Changes merged.
