### ISSUE TITLE
Null Reference Exception in Windows 7 due to SEGOEUI font

### ISSUE THREAD

**Issue by vijayganeshpk** [ishegatron/Sentinel#15]
Hi,
  Thank you for the application, but a known issue when loading the app in Windows 7 as discussed at http://stackoverflow.com/a/27911618

**Comment by ishegatron** [comment]
@vijaysg I could not recreate any errors in Windows 7, but I removed the reference to SEGOEUI.TFF anyways.  Please try the latest commit 43721b1001b24c3ddbf152a1dbfa9fbf94ec14a3 and see if your machine experiences the same error.
