### ISSUE TITLE
NLog 4 - logging exceptions

### ISSUE THREAD

**Issue by pgorbar** [ishegatron/Sentinel#16]
Is it possible to log exception with NLog 4?
Logger.Error(ex, "message") doesn't work for me even when setting custom layout. Logger.ErrorException(...) is obsolete in this version.

(Probably, it's related to #2, but even using EXCEPTION keyword in layout didn't work for me)

**Comment by ishegatron** [comment]
@pgorbar To my knowledge, Sentinel has not been tested with NLog 4, and the release notes list several breaking changes.  Unfortunately, it will be awhile before I can get around to testing it, but I will happily take anyone's pull request.

Also, the fix to #2 has not been deployed yet, so you'd have to get the latest code to see if that fixes your issue.

**Comment by pgorbar** [comment]
@ishegatron Thanks for the info. I've tested with build of the latest sources, but it's possible I setup it wrong.

**Comment by ShaneCourtrille** [comment]
I had no problem getting exceptions to appear correctly with NLog4 and the latest source.  I can create a PR with the NLog 4 test if there is any interest?

**Comment by ishegatron** [comment]
@ShaneCourtrille Sure thing, thanks for contributing!  I guess this issue is resolved.

**Comment by ShaneCourtrille** [comment]
Oddly enough the original Sentinel required a change to work with NLog4 apparently

https://sentinel.codeplex.com/workitem/7533

I can't find the actual change though as there is no obvious way to track that kind of thing back on codeplex.  It would be nice if he moved to github _sigh_
