### ISSUE TITLE
Can I use this in an app?

### ISSUE THREAD

**Issue by tofutim** [ishegatron/Sentinel#17]
Hi, can I use this in an app that is logging using log4net? Looks fantastic. That is, rather than using UDP to transmit to another app, just have this UI embedded.

**Comment by ishegatron** [comment]
@tofutim I don't have a problem with you borrowing from this project, although I'm not the originator.  You should [post on the discussion forum at the original site](http://sentinel.codeplex.com/) if you'd like to ask the originator's permission.
