### ISSUE TITLE
configuration file for Log4Net

### ISSUE THREAD

**Issue by kbalint** [ishegatron/Sentinel#18]
Hello, I tried the original and this fork too, but if I save my Log4net session via File->Save session, and try to reload it, it does not work. I need to go through all the steps in the wizard every time to make it work.
Any hints on this? Thanks!

Edit: as I see from debugging the code, in ProviderManager.cs -> providerManager.GetInstances() method the providerInstances variable's count is always 0.

**Comment by ishegatron** [comment]
@kbalint Resolved by #19
