### ISSUE TITLE
How do you log exceptions

### ISSUE THREAD

**Issue by AlquistArj** [ishegatron/Sentinel#2]
How do you log exceptions from NLog?
Andrew

**Comment by mydiscogr** [comment]
no, because I use universal app, and nlog is not supported for that platform, I write my own  udp class for comunication, bt sentinel do not works :(, I use now Log2Console, but is not great, I love LogCat because you can add tag and filter it, and It's perfect for debugging operation

**Comment by ishegatron** [comment]
@AlquistArj : If you are trying to log internal exceptions from NLog, this site has a pretty good tutorial: [Internal Logging](https://github.com/NLog/NLog/wiki/Internal-Logging).

If you are trying to log exceptions from NLog using the ErrorException, WarnException, or similar methods, it seems to require a change to your layout.  See this article for a good tutorial: [Things your Dad never told you about NLog](http://www.danesparza.net/2014/06/things-your-dad-never-told-you-about-nlog/)

**Comment by AlquistArj** [comment]
@ishegatron logging exceptions to a text file is fine but I cannot seem to work out how to have Exception information displayed in Sentinel. Has anyone had any luck with this?

**Comment by ishegatron** [comment]
@AlquistArj I don't think the exception feature is fully implemented yet.  In the meantime, you could create a custom classifier to classify incoming log messages as exceptions whenever they have "exception" in the message Description field.

**Comment by ishegatron** [comment]
Commit c601943a6c867c366f3c70ac3672b695f270d1b4 implements marking incoming messages as exceptions.
