### ISSUE TITLE
sentinel hub container docker

### ISSUE THREAD

**Issue by runtimevic** [ishegatron/Sentinel#21]
Hello, 
could you have sentinel in a docker container?
best regards, Víctor

**Comment by ishegatron** [comment]
@runtimevic - Docker is mainly for server applications and Sentinel is a .NET WPF desktop application.  Applications that require a Windows UI aren't typically recommended for Docker according to this documentation:
[Modernizing Traditional .NET Apps with Docker](https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/april/containers-modernizing-traditional-net-apps-with-docker#where-docker-fits-in-net-solutions)

However, if you know of a way to accomplish this and have a good use case for it, I'll be happy to collaborate and accept your pull request.
