### ISSUE TITLE
Error when adding new File Monitoring Provider

### ISSUE THREAD

**Issue by octocat-mona** [ishegatron/Sentinel#3]
When I start Sentinel and try to add a new File Monitoring Provider, an Error dialog is shown (see attachment).

When I debug where this error comes from it passes through `Sentinel.FileMonitor.FileMonitorProviderPage.PropertyChangedHandler`, where the FileName is empty. It looks like that the FileName is set to an empty string which causes the event to fire. Because an empty string is not a valid path the Error is shown.

I think that the FileName property should not be set to `string.Empty` in `Sentinel.FileMonitor.FileMonitorProviderPage.OnLoaded` ?

![call stack](https://cloud.githubusercontent.com/assets/538170/6377598/9ad40630-bd25-11e4-9309-f6dbc5c80e58.jpg)
![error dialog](https://cloud.githubusercontent.com/assets/538170/6377597/9ad223b0-bd25-11e4-987e-dddfbf4613f3.jpg)

**Comment by ishegatron** [comment]
@kpstolk Thanks for addressing this issue.
